Bug 1656148 follow-up - Fix errors on compose window opening. r=kaie DONTBUILD
Fixes two errors that happen when the compose window is opened:
TypeError: can't redefine non-configurable property "FileUtils"
ReferenceError: XPCOMUtils is not defined

I caused the first with the previous commit in this bug ? this patch undoes part of it. I don't know where the second came from.

Differential Revision: https://phabricator.services.mozilla.com/D85546